<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose a Company</name>
   <tag></tag>
   <elementGuidId>f9a24c8b-cd3d-48a8-bf86-ab05a19581cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='company']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#company</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Company&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a28ad8af-79d2-4683-af8f-e16e27707c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>8b5418b3-f761-4c04-8f2c-fcae1f51872f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>574ee4c1-6ad6-46b7-aeab-7bc02c501c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics</value>
      <webElementGuid>7e8b8dba-b8c3-407e-8529-4ff009a263bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company&quot;)</value>
      <webElementGuid>18b0c026-b56b-4ad3-af5d-46b68a312dec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='company']</value>
      <webElementGuid>7892c8d5-aa3a-472e-8065-8f140b2fca83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/form/fieldset/div[4]/div/select</value>
      <webElementGuid>d0134dc0-0c61-402d-a6b5-33ae53266020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/following::select[1]</value>
      <webElementGuid>c0e66a7e-f845-493f-a4dd-aa079bc871dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>ce169a2b-e621-4c0d-9301-89bf24f3f3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>96db967f-70ce-4876-ad04-0e557cef8519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'company' and @name = 'company' and (text() = '-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics' or . = '-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics')]</value>
      <webElementGuid>8de4330c-45a0-4b6f-832b-4bad5b2ac63b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
